In [16]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
# import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt
from matplotlib import ticker

In [17]:
#Das selbe wie unten, aber mit korrekter std Berechnung. Hier nehmen wir bei jedem Shot den Average aller 15 Winkel und berechnen dann die std aus den 400 Avergages jeden Shots

name = "Phasecode_d3_ftqec"         #data = np.array((p, bias, y, y_qec))       
N = 400
angles = 15

file = np.load('text/temp/{}0.npz'.format(name))               #alle nans rausfilteren
clean_file = file
noisepoints = len(clean_file["p"])
biaspoints = len(clean_file["bias"])


faulty = []
all_y, all_y_qec = [], []
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test= np.load("text/temp/{}{}.npz".format(name,i))                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    p = test["p"]
    bias = test["bias"]
    y = test["y"]
    y_qec = test["y_qec"]

    all_y = all_y + list(y.flatten())              #all_y: Länge ist N*angles*noisepoints*bias=400*15*10*10 = 600k Elemente
    all_y_qec = all_y_qec + list(y_qec.flatten())

print("Dead files: ",len(faulty), ", ", faulty)
N = N - len(faulty)

data = np.full((noisepoints, 5, biaspoints), np.nan)      #Zahl zwischen noisepoints und biaspoints: bias+y+err + y_qec+err_qec = 3 + 2 = 5    FALLS mit QEC in npz file, sonst nur 3
for ö in range(noisepoints):
    data[ö, 0] = clean_file["bias"]
    err, err_qec = [], []
    y, y_qec = [], []
    for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
        hmm, hmm1 = [], []
        for i in range(N):
            avg_per_shot, avgqec_per_shot = 0, 0
            for k in range(angles):
                avg_per_shot += all_y[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j + angles*ö]
                avgqec_per_shot += all_y_qec[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j+angles*ö]
            avg_per_shot, avgqec_per_shot = avg_per_shot/angles, avgqec_per_shot/angles
            hmm.append(avg_per_shot), hmm1.append(avgqec_per_shot)
        err.append(np.std(hmm)/np.sqrt(N)), err_qec.append(np.std(hmm1)/np.sqrt(N))
        y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
        print("y: {}, std: {}, err: {}".format(np.mean(hmm), np.std(hmm), np.std(hmm)/np.sqrt(N)))
    data[ö, 1] = y
    data[ö, 2] = y_qec
    data[ö, 3] = err
    data[ö, 4] = err_qec

total = np.array(data, dtype=object)
print(np.shape(total))

Dead files:  0 ,  []
y: 0.04777083333333334, std: 0.015435672406438563, err: 0.0007717836203219281
y: 0.050687499999999996, std: 0.016384472980877692, err: 0.0008192236490438846
y: 0.048999999999999995, std: 0.01678210025261704, err: 0.000839105012630852
y: 0.049416666666666664, std: 0.017149465492156502, err: 0.0008574732746078251
y: 0.04935416666666667, std: 0.015682380749497897, err: 0.0007841190374748948
y: 0.0513125, std: 0.017315884145777827, err: 0.0008657942072888914
y: 0.050041666666666665, std: 0.015534404022470038, err: 0.0007767202011235019
y: 0.12747916666666664, std: 0.0338183400173305, err: 0.001690917000866525
y: 0.12349999999999998, std: 0.032304540444546385, err: 0.0016152270222273193
y: 0.12485416666666665, std: 0.0349326671274738, err: 0.0017466333563736901
y: 0.11918749999999999, std: 0.03263433109429734, err: 0.0016317165547148672
y: 0.11712499999999998, std: 0.0317618908179808, err: 0.0015880945408990401
y: 0.11825, std: 0.03373085876957972, err: 0.00168654293847

In [ ]:
# name = "Phasecode_d3_idealqec"         #data = np.array((p, bias, y, y_qec))       
# N = 400
# angles = 15

# file = np.load('text/temp/{}0.npz'.format(name))               #alle nans rausfilteren
# clean_file = file
# noisepoints = len(clean_file["p"])
# biaspoints = len(clean_file["bias"])


# faulty = []
# all_y, all_y_qec = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test= np.load("text/temp/{}{}.npz".format(name,i))                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     p = test["p"]
#     bias = test["bias"]
#     y = test["y"]
#     y_qec = test["y_qec"]

#     all_y = all_y + list(y.flatten())              #all_y: Länge ist N*angles*noisepoints*bias=400*15*10*10 = 600k Elemente
#     all_y_qec = all_y_qec + list(y_qec.flatten())

# print("Dead files: ",len(faulty), ", ", faulty)
# N = N - len(faulty)

# data = np.full((noisepoints, 5, biaspoints), np.nan)      #Zahl zwischen noisepoints und biaspoints: bias+y+err + y_qec+err_qec = 3 + 2 = 5    FALLS mit QEC in npz file, sonst nur 3
# for ö in range(noisepoints):
#     data[ö, 0] = clean_file["bias"]
#     err, err_qec = [], []
#     y, y_qec = [], []
#     for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#         hmm, hmm1 = [], []
#         for i in range(N):
#             for k in range(angles):
#                 hmm.append(all_y[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j + angles*ö])
#                 hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j+angles*ö])
#         err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#         y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
#     data[ö, 1] = y
#     data[ö, 2] = y_qec
#     data[ö, 3] = err
#     data[ö, 4] = err_qec

# total = np.array(data, dtype=object)
# print(np.shape(total))

Dead files:  0 ,  []
(6, 5, 7)


In [4]:
# name = "Repcode_d5"         #data = np.array((p, bias, y, y_qec))         code 1
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]
# noisepoints = len(p)

# b_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[1]               #alle nans rausfiltern
# b = b_all[~np.isnan(b_all)]
# biaspoints = len(b)

# faulty = []
# all_y, all_y_qec = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*noisepoints*bias=10*15*10*10 = 15000 Elemente
#     all_y_qec = all_y_qec + list(test[-1])

# print("Dead files: ",len(faulty), ", ", faulty)
# N = N - len(faulty)

# data = np.full((noisepoints, 5, biaspoints), np.nan)
# for ö in range(noisepoints):
#     data[ö, 0] = b
#     err, err_qec = [], []
#     y, y_qec = [], []
#     for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#         hmm, hmm1 = [], []
#         for i in range(N):
#             for k in range(angles):
#                 hmm.append(all_y[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#                 hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#         err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#         y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
#     data[ö, 1] = y
#     data[ö, 2] = y_qec
#     data[ö, 3] = err
#     data[ö, 4] = err_qec

# total = np.array(data, dtype=object)
# print(np.shape(total))

In [18]:
print(total)

np.save("text/{}.npy".format(name), data)

[[[-10000.0 -100.0 -10.0 0.0 10.0 100.0 10000.0]
  [0.04777083333333334 0.050687499999999996 0.048999999999999995
   0.049416666666666664 0.04935416666666667 0.0513125
   0.050041666666666665]
  [0.050166666666666665 0.050479166666666665 0.049812499999999996
   0.049666666666666665 0.050625 0.05052083333333334
   0.049104166666666664]
  [0.0007717836203219281 0.0008192236490438846 0.000839105012630852
   0.0008574732746078251 0.0007841190374748948 0.0008657942072888914
   0.0007767202011235019]
  [0.0008306832863505935 0.000807860014989877 0.0007679556363325943
   0.0007434202116643797 0.0007670939705943608 0.0007653060560161536
   0.000770658060027994]]

 [[-10000.0 -100.0 -10.0 0.0 10.0 100.0 10000.0]
  [0.12747916666666664 0.12349999999999998 0.12485416666666665
   0.11918749999999999 0.11712499999999998 0.11825 0.11587499999999999]
  [0.11408333333333331 0.1166875 0.1155625 0.12075 0.12149999999999998
   0.12202083333333334 0.12347916666666667]
  [0.001690917000866525 0.00161522702

In [ ]:
# name = "Repcode_d3_bias0_9"                       #alter Repcode, wo man für jede Simulation einen Plot hat   code 0
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]

# datapoints = len(p)

# faulty = []
# all_y, all_y1 = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*datapoints=10*15*10 = 1500 Elemente
#     all_y1 = all_y1 + list(test[-1])

# err, err_qec = [], []
# y, y_qec = [], []

# for j in range(datapoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#     hmm, hmm1 = [], []
#     for i in range(N):
#         for k in range(angles):
#             hmm.append(all_y[k+angles*datapoints*i+angles*j])
#             hmm1.append(all_y1[k+angles*datapoints*i+angles*j])
#     err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#     y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))

# print("Dead files: ",len(faulty), ", ", faulty)
# total = np.array((p,y,y_qec,err,err_qec))
# print(total)

In [2]:
N = 400                               #code OG
total = np.zeros((3,4))
faulty = []
name = "FTSteane_qec_4_7_neww"
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/(N-len(faulty))
print("Dead files: ",len(faulty), ", ", faulty)
print(total)

Dead files:  0 ,  []
[[0.00044444 0.00055556 0.00066667 0.00077778]
 [0.16902083 0.18941667 0.19575    0.20435417]
 [0.05736907 0.06032394 0.0592164  0.06022282]]


In [3]:
#np.savetxt('text/FTSteane_3rd_q.txt', total, delimiter=",")
#np.savetxt('text/FTRotSurf_3rd_f+.txt', total, delimiter=",")
#np.savetxt('text/FTCarbon_e.txt', total, delimiter=",")

np.savetxt("text/{}.txt".format(name), total, delimiter=",")

#np.savetxt('text/FTCarbon_3rd_c+.txt', total, delimiter=",")

#np.savetxt('text/RotSurfFinal_d.txt', total, delimiter=",")
#np.savetxt('text/SteaneFinal_a+++.txt', total, delimiter=",")