In [4]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
# import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt
from matplotlib import ticker

In [5]:
name = "Repcodez_d3_qec"         #data = np.array((p, bias, y, y_qec))       
N = 400
angles = 15

file = np.load('text/temp/{}0.npz'.format(name))               #alle nans rausfilteren
clean_file = file
noisepoints = len(clean_file["p"])
biaspoints = len(clean_file["bias"])


faulty = []
all_y, all_y_qec = [], []
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test= np.load("text/temp/{}{}.npz".format(name,i))                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    p = test["p"]
    bias = test["bias"]
    y = test["y"]
    y_qec = test["y_qec"]

    all_y = all_y + list(y.flatten())              #all_y: Länge ist N*angles*noisepoints*bias=400*15*10*10 = 600k Elemente
    all_y_qec = all_y_qec + list(y_qec.flatten())

print("Dead files: ",len(faulty), ", ", faulty)
N = N - len(faulty)

data = np.full((noisepoints, 5, biaspoints), np.nan)      #Zahl zwischen noisepoints und biaspoints: bias+y+err + y_qec+err_qec = 3 + 2 = 5    FALLS mit QEC in npz file, sonst nur 3
for ö in range(noisepoints):
    data[ö, 0] = clean_file["bias"]
    err, err_qec = [], []
    y, y_qec = [], []
    for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
        hmm, hmm1 = [], []
        for i in range(N):
            for k in range(angles):
                hmm.append(all_y[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j + angles*ö])
                hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j+angles*ö])
        err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
        y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
    data[ö, 1] = y
    data[ö, 2] = y_qec
    data[ö, 3] = err
    data[ö, 4] = err_qec

total = np.array(data, dtype=object)
print(np.shape(total))

Dead files:  0 ,  []
(10, 5, 7)


In [4]:
# name = "Repcode_d5"         #data = np.array((p, bias, y, y_qec))         code 1
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]
# noisepoints = len(p)

# b_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[1]               #alle nans rausfiltern
# b = b_all[~np.isnan(b_all)]
# biaspoints = len(b)

# faulty = []
# all_y, all_y_qec = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*noisepoints*bias=10*15*10*10 = 15000 Elemente
#     all_y_qec = all_y_qec + list(test[-1])

# print("Dead files: ",len(faulty), ", ", faulty)
# N = N - len(faulty)

# data = np.full((noisepoints, 5, biaspoints), np.nan)
# for ö in range(noisepoints):
#     data[ö, 0] = b
#     err, err_qec = [], []
#     y, y_qec = [], []
#     for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#         hmm, hmm1 = [], []
#         for i in range(N):
#             for k in range(angles):
#                 hmm.append(all_y[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#                 hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#         err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#         y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
#     data[ö, 1] = y
#     data[ö, 2] = y_qec
#     data[ö, 3] = err
#     data[ö, 4] = err_qec

# total = np.array(data, dtype=object)
# print(np.shape(total))

In [6]:
print(total)

np.save("text/{}.npy".format(name), data)

[[[-10000.0 -100.0 -10.0 0.0 10.0 100.0 10000.0]
  [0.07308333333333333 0.0705625 0.071625 0.07052083333333334
   0.06872916666666666 0.0693125 0.0704375]
  [0.07004166666666667 0.07341666666666667 0.07035416666666666
   0.06991666666666667 0.07047916666666666 0.06991666666666667
   0.07170833333333333]
  [0.002022335066295981 0.0019797190566852602 0.0020173967772712546
   0.001971288688733516 0.0019438850695895446 0.0019339324794494365
   0.00197046403560811]
  [0.0019961072503982824 0.0020562022256073436 0.0019565940673345363
   0.001955547368196245 0.002001361497663204 0.0019605348146001537
   0.0019968985646033237]]

 [[-10000.0 -100.0 -10.0 0.0 10.0 100.0 10000.0]
  [0.235875 0.23239583333333333 0.228125 0.2290625 0.22208333333333333
   0.22525 0.2259375]
  [0.19133333333333333 0.19733333333333333 0.1985 0.21254166666666666
   0.2264375 0.2298125 0.22839583333333333]
  [0.003284762405791323 0.0032389633539479244 0.003231669057288096
   0.003254981658774491 0.003199102883506446 0.0

In [ ]:
# name = "Repcode_d3_bias0_9"                       #alter Repcode, wo man für jede Simulation einen Plot hat   code 0
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]

# datapoints = len(p)

# faulty = []
# all_y, all_y1 = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*datapoints=10*15*10 = 1500 Elemente
#     all_y1 = all_y1 + list(test[-1])

# err, err_qec = [], []
# y, y_qec = [], []

# for j in range(datapoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#     hmm, hmm1 = [], []
#     for i in range(N):
#         for k in range(angles):
#             hmm.append(all_y[k+angles*datapoints*i+angles*j])
#             hmm1.append(all_y1[k+angles*datapoints*i+angles*j])
#     err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#     y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))

# print("Dead files: ",len(faulty), ", ", faulty)
# total = np.array((p,y,y_qec,err,err_qec))
# print(total)

In [2]:
N = 400                               #code OG
total = np.zeros((3,4))
faulty = []
name = "FTSteane_qec_4_7_new"
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/(N-len(faulty))
print("Dead files: ",len(faulty), ", ", faulty)
print(total)

Dead files:  0 ,  []
[[0.00044444 0.00055556 0.00066667 0.00077778]
 [0.165625   0.17764583 0.18875    0.20308333]
 [0.05608191 0.05771539 0.05850026 0.06034437]]


In [3]:
#np.savetxt('text/FTSteane_3rd_q.txt', total, delimiter=",")
#np.savetxt('text/FTRotSurf_3rd_f+.txt', total, delimiter=",")
#np.savetxt('text/FTCarbon_e.txt', total, delimiter=",")

np.savetxt("text/{}.txt".format(name), total, delimiter=",")

#np.savetxt('text/FTCarbon_3rd_c+.txt', total, delimiter=",")

#np.savetxt('text/RotSurfFinal_d.txt', total, delimiter=",")
#np.savetxt('text/SteaneFinal_a+++.txt', total, delimiter=",")