In [25]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
# import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt
from matplotlib import ticker

In [ ]:
# #Timos Approach: Nur die perfekten 7 Winkel nehmen, pos/neg Performance zulassen, also Inputwinkel wird der SK-Winkel genommen, nicht die exakten Inputwinkel, dann für jeden einzelnen Winkel den Average über alle Shots nehmen

# name = "Phasecode_d3_sk_idealqec"         #data = np.array((p, bias, y, y_qec))       
# N = 400
# angles = 7

# file = np.load('text/temp/{}0.npz'.format(name))               #alle nans rausfilteren
# clean_file = file
# noisepoints = len(clean_file["p"])
# biaspoints = len(clean_file["bias"])

# sk_angles = np.loadtxt("Upload/SK_angles.txt")

# faulty = []
# all_y, all_y_qec = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test= np.load("text/temp/{}{}.npz".format(name,i))                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     p = test["p"]
#     bias = test["bias"]
#     y = test["y"]
#     y_qec = test["y_qec"]

#     all_y = all_y + list(y.flatten())              #all_y: Länge ist N*angles*noisepoints*bias=400*15*10*10 = 600k Elemente
#     all_y_qec = all_y_qec + list(y_qec.flatten())

# print("Dead files: ",len(faulty), ", ", faulty)
# N = N - len(faulty)

# data = np.full((noisepoints, 5, biaspoints), np.nan)      #Zahl zwischen noisepoints und biaspoints: bias+y+err + y_qec+err_qec = 3 + 2 = 5    FALLS mit QEC in npz file, sonst nur 3
# for ö in range(noisepoints):
#     data[ö, 0] = clean_file["bias"]
#     err, err_qec = [], []
#     y, y_qec = [], []
#     for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#         hmm, hmm1 = [], []                          #hmm --> No QEC, hmm1 --> QEC
#         for k in range(angles):
#             hmm_oneangle, hmm1_oneangle = [], []
#             for i in range(N):
#                 hmm_oneangle.append(all_y[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j + angles*ö])
#                 hmm1_oneangle.append(all_y_qec[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j+angles*ö])
#             diff, diff1 = [],[]
#             for q in hmm_oneangle:
#                 if np.abs(q-sk_angles[2*k+1]) <= 1-np.abs(q-sk_angles[2*k+1]):
#                     diff.append(q-sk_angles[2*k+1])
#                 else:
#                     diff.append(1-np.abs(q-sk_angles[2*k+1]))
#             for q in hmm1_oneangle:
#                 if np.abs(q-sk_angles[2*k+1]) <= 1-np.abs(q-sk_angles[2*k+1]):
#                     diff1.append(q-sk_angles[2*k+1])
#                 else:
#                     diff1.append(1-np.abs(q-sk_angles[2*k+1]))
#             avg, avg1 = np.mean(diff), np.mean(diff1)
#             print("avg of angle {}: ".format(2*k+1), avg)
#             hmm.append(avg), hmm1.append(avg1)
#         err.append(np.std(hmm)/np.sqrt(N)), err_qec.append(np.std(hmm1)/np.sqrt(N))
#         y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
#     data[ö, 1] = y
#     data[ö, 2] = y_qec
#     data[ö, 3] = err
#     data[ö, 4] = err_qec

# total = np.array(data, dtype=object)
# print(np.shape(total))

Dead files:  0 ,  []
avg of angle 1:  0.005015858161499984
avg of angle 3:  0.0
avg of angle 5:  0.003174411839086142
avg of angle 7:  0.0
avg of angle 9:  -0.000888088160913858
avg of angle 11:  0.0
avg of angle 13:  0.000986911839086142
avg of angle 1:  0.0016119118390862796
avg of angle 3:  0.0
avg of angle 5:  0.002236911839086142
avg of angle 7:  0.0
avg of angle 9:  0.001299411839086142
avg of angle 11:  0.0
avg of angle 13:  0.000986911839086142
avg of angle 1:  0.0053283581614999844
avg of angle 3:  0.0
avg of angle 5:  0.001299411839086142
avg of angle 7:  0.0
avg of angle 9:  0.001924411839086142
avg of angle 11:  0.0
avg of angle 13:  -0.001513088160913858
avg of angle 1:  0.005339542720695416
avg of angle 3:  0.0
avg of angle 5:  0.004413227279890711
avg of angle 7:  0.0
avg of angle 9:  -0.001200588160913858
avg of angle 11:  0.0
avg of angle 13:  0.001611911839086142
avg of angle 1:  0.003788227279890849
avg of angle 3:  0.0
avg of angle 5:  0.0041007272798907115
avg of a

In [ ]:
#Das selbe wie unten, aber mit korrekter std Berechnung. Hier nehmen wir bei jedem Shot den Average aller 15 Winkel und berechnen dann die std aus den 400 Avergages jeden Shots

name = "Phasecode_d3_exactangles_ftqec"         #data = np.array((p, bias, y, y_qec))       
N = 400
angles = 7

file = np.load('text/temp/{}0.npz'.format(name))               #alle nans rausfilteren
clean_file = file
noisepoints = len(clean_file["p"])
biaspoints = len(clean_file["bias"])


faulty = []
all_y, all_y_qec = [], []
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test= np.load("text/temp/{}{}.npz".format(name,i))                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    p = test["p"]
    bias = test["bias"]
    y = test["y"]
    y_qec = test["y_qec"]

    all_y = all_y + list(y.flatten())              #all_y: Länge ist N*angles*noisepoints*bias=400*15*10*10 = 600k Elemente
    all_y_qec = all_y_qec + list(y_qec.flatten())

print("Dead files: ",len(faulty), ", ", faulty)
N = N - len(faulty)

data = np.full((noisepoints, 5, biaspoints), np.nan)      #Zahl zwischen noisepoints und biaspoints: bias+y+err + y_qec+err_qec = 3 + 2 = 5    FALLS mit QEC in npz file, sonst nur 3
for ö in range(noisepoints):
    data[ö, 0] = clean_file["bias"]
    err, err_qec = [], []
    y, y_qec = [], []
    for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
        hmm, hmm1 = [], []
        for i in range(N):
            avg_per_shot, avgqec_per_shot = 0, 0
            for k in range(angles):
                avg_per_shot += all_y[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j + angles*ö]
                avgqec_per_shot += all_y_qec[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j+angles*ö]
            avg_per_shot, avgqec_per_shot = avg_per_shot/angles, avgqec_per_shot/angles
            hmm.append(avg_per_shot), hmm1.append(avgqec_per_shot)
        err.append(np.std(hmm)/np.sqrt(N)), err_qec.append(np.std(hmm1)/np.sqrt(N))
        y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
        print("y: {}, std: {}, err: {}".format(np.mean(hmm), np.std(hmm), np.std(hmm)/np.sqrt(N)))
    data[ö, 1] = y
    data[ö, 2] = y_qec
    data[ö, 3] = err
    data[ö, 4] = err_qec

total = np.array(data, dtype=object)
print(np.shape(total))

Dead files:  0 ,  []
y: 0.002232142857142857, std: 0.009268097987511917, err: 0.00046340489937559586
y: 0.002544642857142857, std: 0.010057135089029062, err: 0.0005028567544514531
y: 0.0016964285714285712, std: 0.008202145531903871, err: 0.0004101072765951935
y: 0.0020089285714285712, std: 0.00818012598295031, err: 0.00040900629914751547
y: 0.002232142857142857, std: 0.009688631434915492, err: 0.0004844315717457746
y: 0.0023660714285714283, std: 0.007679479805073427, err: 0.00038397399025367134
y: 0.0029464285714285708, std: 0.010606225910342682, err: 0.0005303112955171341
y: 0.07638392857142857, std: 0.04877482933238271, err: 0.0024387414666191356
y: 0.08049107142857143, std: 0.04869123796921259, err: 0.0024345618984606297
y: 0.07870535714285713, std: 0.04768707705699518, err: 0.002384353852849759
y: 0.07647321428571428, std: 0.05095608149876896, err: 0.0025478040749384477
y: 0.07357142857142858, std: 0.04932775122399487, err: 0.0024663875611997434
y: 0.07428571428571427, std: 0.04880

In [ ]:
# name = "Phasecode_d3_idealqec"         #data = np.array((p, bias, y, y_qec))       
# N = 400
# angles = 15

# file = np.load('text/temp/{}0.npz'.format(name))               #alle nans rausfilteren
# clean_file = file
# noisepoints = len(clean_file["p"])
# biaspoints = len(clean_file["bias"])


# faulty = []
# all_y, all_y_qec = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test= np.load("text/temp/{}{}.npz".format(name,i))                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     p = test["p"]
#     bias = test["bias"]
#     y = test["y"]
#     y_qec = test["y_qec"]

#     all_y = all_y + list(y.flatten())              #all_y: Länge ist N*angles*noisepoints*bias=400*15*10*10 = 600k Elemente
#     all_y_qec = all_y_qec + list(y_qec.flatten())

# print("Dead files: ",len(faulty), ", ", faulty)
# N = N - len(faulty)

# data = np.full((noisepoints, 5, biaspoints), np.nan)      #Zahl zwischen noisepoints und biaspoints: bias+y+err + y_qec+err_qec = 3 + 2 = 5    FALLS mit QEC in npz file, sonst nur 3
# for ö in range(noisepoints):
#     data[ö, 0] = clean_file["bias"]
#     err, err_qec = [], []
#     y, y_qec = [], []
#     for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#         hmm, hmm1 = [], []
#         for i in range(N):
#             for k in range(angles):
#                 hmm.append(all_y[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j + angles*ö])
#                 hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j+angles*ö])
#         err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#         y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
#     data[ö, 1] = y
#     data[ö, 2] = y_qec
#     data[ö, 3] = err
#     data[ö, 4] = err_qec

# total = np.array(data, dtype=object)
# print(np.shape(total))

Dead files:  0 ,  []
(6, 5, 7)


In [29]:
print(total)

np.save("text/{}.npy".format(name), data)

[[[-10000.0 -100.0 -10.0 0.0 10.0 100.0 10000.0]
  [0.0011841562398226299 0.0008764496223349578 0.0010055848112512015
   0.001452013382679773 0.0020339683197076923 0.0008318067651921008
   0.001715077143024588]
  [0.0018553968911362631 0.0014105661138784679 0.0008748518281641824
   0.0018537990969654874 0.0009609419541083445 0.002115265063139527
   0.002032370525536916]
  [9.852997581940651e-05 4.177897999797029e-05 0.00010175998168933655
   0.00011536984496275982 9.281131746218834e-05 6.31099362415411e-05
   0.00012122810689361807]
  [8.549438948060821e-05 7.461479906329971e-05 5.470584686668612e-05
   0.00010096388370912324 8.022232378962226e-05 0.00012391524184847492
   0.00011291713921816564]]

 [[-10000.0 -100.0 -10.0 0.0 10.0 100.0 10000.0]
  [0.005027949197704073 0.010212816423319735 0.006072215268229449
   0.015528512011661288 0.00145003406995353 0.009245053713713864
   0.006161500982515161]
  [0.00210388974466636 0.0028612205219241543 0.0039262579166696255
   0.005120430500331

In [4]:
# name = "Repcode_d5"         #data = np.array((p, bias, y, y_qec))         code 1
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]
# noisepoints = len(p)

# b_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[1]               #alle nans rausfiltern
# b = b_all[~np.isnan(b_all)]
# biaspoints = len(b)

# faulty = []
# all_y, all_y_qec = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*noisepoints*bias=10*15*10*10 = 15000 Elemente
#     all_y_qec = all_y_qec + list(test[-1])

# print("Dead files: ",len(faulty), ", ", faulty)
# N = N - len(faulty)

# data = np.full((noisepoints, 5, biaspoints), np.nan)
# for ö in range(noisepoints):
#     data[ö, 0] = b
#     err, err_qec = [], []
#     y, y_qec = [], []
#     for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#         hmm, hmm1 = [], []
#         for i in range(N):
#             for k in range(angles):
#                 hmm.append(all_y[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#                 hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#         err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#         y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
#     data[ö, 1] = y
#     data[ö, 2] = y_qec
#     data[ö, 3] = err
#     data[ö, 4] = err_qec

# total = np.array(data, dtype=object)
# print(np.shape(total))

In [ ]:
# name = "Repcode_d3_bias0_9"                       #alter Repcode, wo man für jede Simulation einen Plot hat   code 0
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]

# datapoints = len(p)

# faulty = []
# all_y, all_y1 = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*datapoints=10*15*10 = 1500 Elemente
#     all_y1 = all_y1 + list(test[-1])

# err, err_qec = [], []
# y, y_qec = [], []

# for j in range(datapoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#     hmm, hmm1 = [], []
#     for i in range(N):
#         for k in range(angles):
#             hmm.append(all_y[k+angles*datapoints*i+angles*j])
#             hmm1.append(all_y1[k+angles*datapoints*i+angles*j])
#     err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#     y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))

# print("Dead files: ",len(faulty), ", ", faulty)
# total = np.array((p,y,y_qec,err,err_qec))
# print(total)

In [2]:
N = 400                               #code OG
total = np.zeros((3,4))
faulty = []
name = "FTSteane_qec_4_7_neww"
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/(N-len(faulty))
print("Dead files: ",len(faulty), ", ", faulty)
print(total)

Dead files:  0 ,  []
[[0.00044444 0.00055556 0.00066667 0.00077778]
 [0.16902083 0.18941667 0.19575    0.20435417]
 [0.05736907 0.06032394 0.0592164  0.06022282]]


In [3]:
#np.savetxt('text/FTSteane_3rd_q.txt', total, delimiter=",")
#np.savetxt('text/FTRotSurf_3rd_f+.txt', total, delimiter=",")
#np.savetxt('text/FTCarbon_e.txt', total, delimiter=",")

np.savetxt("text/{}.txt".format(name), total, delimiter=",")

#np.savetxt('text/FTCarbon_3rd_c+.txt', total, delimiter=",")

#np.savetxt('text/RotSurfFinal_d.txt', total, delimiter=",")
#np.savetxt('text/SteaneFinal_a+++.txt', total, delimiter=",")