In [5]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
# import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt
from matplotlib import ticker

In [6]:
name = "Repcodez_d3_idealqec"         #data = np.array((p, bias, y, y_qec))       
N = 400
angles = 15

file = np.load('text/temp/{}0.npz'.format(name))               #alle nans rausfilteren
clean_file = file
noisepoints = len(clean_file["p"])
biaspoints = len(clean_file["bias"])


faulty = []
all_y, all_y_qec = [], []
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test= np.load("text/temp/{}{}.npz".format(name,i))                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    p = test["p"]
    bias = test["bias"]
    y = test["y"]
    y_qec = test["y_qec"]

    all_y = all_y + list(y.flatten())              #all_y: Länge ist N*angles*noisepoints*bias=400*15*10*10 = 600k Elemente
    all_y_qec = all_y_qec + list(y_qec.flatten())

print("Dead files: ",len(faulty), ", ", faulty)
N = N - len(faulty)

data = np.full((noisepoints, 5, biaspoints), np.nan)      #Zahl zwischen noisepoints und biaspoints: bias+y+err + y_qec+err_qec = 3 + 2 = 5    FALLS mit QEC in npz file, sonst nur 3
for ö in range(noisepoints):
    data[ö, 0] = clean_file["bias"]
    err, err_qec = [], []
    y, y_qec = [], []
    for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
        hmm, hmm1 = [], []
        for i in range(N):
            for k in range(angles):
                hmm.append(all_y[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j + angles*ö])
                hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j+angles*ö])
        err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
        y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
    data[ö, 1] = y
    data[ö, 2] = y_qec
    data[ö, 3] = err
    data[ö, 4] = err_qec

total = np.array(data, dtype=object)
print(np.shape(total))

Dead files:  0 ,  []
(5, 5, 5)


In [4]:
# name = "Repcode_d5"         #data = np.array((p, bias, y, y_qec))         code 1
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]
# noisepoints = len(p)

# b_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[1]               #alle nans rausfiltern
# b = b_all[~np.isnan(b_all)]
# biaspoints = len(b)

# faulty = []
# all_y, all_y_qec = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*noisepoints*bias=10*15*10*10 = 15000 Elemente
#     all_y_qec = all_y_qec + list(test[-1])

# print("Dead files: ",len(faulty), ", ", faulty)
# N = N - len(faulty)

# data = np.full((noisepoints, 5, biaspoints), np.nan)
# for ö in range(noisepoints):
#     data[ö, 0] = b
#     err, err_qec = [], []
#     y, y_qec = [], []
#     for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#         hmm, hmm1 = [], []
#         for i in range(N):
#             for k in range(angles):
#                 hmm.append(all_y[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#                 hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#         err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#         y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
#     data[ö, 1] = y
#     data[ö, 2] = y_qec
#     data[ö, 3] = err
#     data[ö, 4] = err_qec

# total = np.array(data, dtype=object)
# print(np.shape(total))

In [7]:
print(total)

np.save("text/{}.npy".format(name), data)

[[[-10000.0 -100.0 0.0 100.0 10000.0]
  [0.07360416666666666 0.07045833333333333 0.07060416666666666
   0.07345833333333333 0.07022916666666666]
  [0.06852083333333334 0.072375 0.07235416666666666 0.06841666666666667
   0.07095833333333333]
  [0.0020626737966898514 0.001955414417452598 0.002004311740389213
   0.002059645260606068 0.0019632097789068215]
  [0.001927852305285695 0.0020354448138620164 0.0020185459384021495
   0.0019324033922476877 0.0019796630225546894]]

 [[-10000.0 -100.0 0.0 100.0 10000.0]
  [0.14710416666666667 0.14985416666666668 0.20558333333333334
   0.22897916666666668 0.2324375]
  [0.11725 0.12335416666666667 0.1986875 0.23239583333333333
   0.23364583333333333]
  [0.0029052888071002575 0.0029328266484543986 0.003213026149448062
   0.003227036920887821 0.0032261113570128393]
  [0.0026247466808987283 0.0026776272010237048 0.0031635770632417732
   0.003241106677834977 0.0032244788441779123]]

 [[-10000.0 -100.0 0.0 100.0 10000.0]
  [0.19489583333333332 0.197875 0.24

In [ ]:
# name = "Repcode_d3_bias0_9"                       #alter Repcode, wo man für jede Simulation einen Plot hat   code 0
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]

# datapoints = len(p)

# faulty = []
# all_y, all_y1 = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*datapoints=10*15*10 = 1500 Elemente
#     all_y1 = all_y1 + list(test[-1])

# err, err_qec = [], []
# y, y_qec = [], []

# for j in range(datapoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#     hmm, hmm1 = [], []
#     for i in range(N):
#         for k in range(angles):
#             hmm.append(all_y[k+angles*datapoints*i+angles*j])
#             hmm1.append(all_y1[k+angles*datapoints*i+angles*j])
#     err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#     y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))

# print("Dead files: ",len(faulty), ", ", faulty)
# total = np.array((p,y,y_qec,err,err_qec))
# print(total)

In [3]:
N = 400                               #code OG
total = np.zeros((3,3))
faulty = []
name = "FTSteane_qec_4_6"
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/(N-len(faulty))
print("Dead files: ",len(faulty), ", ", faulty)
print(total)

Dead files:  0 ,  []
[[0.00044444 0.00055556 0.00066667]
 [0.1658125  0.18225    0.19520833]
 [0.05711954 0.05873767 0.0606191 ]]


In [4]:
#np.savetxt('text/FTSteane_3rd_q.txt', total, delimiter=",")
#np.savetxt('text/FTRotSurf_3rd_f+.txt', total, delimiter=",")
#np.savetxt('text/FTCarbon_e.txt', total, delimiter=",")

np.savetxt("text/{}.txt".format(name), total, delimiter=",")

#np.savetxt('text/FTCarbon_3rd_c+.txt', total, delimiter=",")

#np.savetxt('text/RotSurfFinal_d.txt', total, delimiter=",")
#np.savetxt('text/SteaneFinal_a+++.txt', total, delimiter=",")