In [10]:
import numpy as np
from tqdm import tqdm_notebook as tqdm
# import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt
from matplotlib import ticker

In [11]:
name = "Repcodez_d3_nftqec"         #data = np.array((p, bias, y, y_qec))       
N = 400
angles = 15

file = np.load('text/temp/{}0.npz'.format(name))               #alle nans rausfilteren
clean_file = file
noisepoints = len(clean_file["p"])
biaspoints = len(clean_file["bias"])


faulty = []
all_y, all_y_qec = [], []
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test= np.load("text/temp/{}{}.npz".format(name,i))                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    p = test["p"]
    bias = test["bias"]
    y = test["y"]
    y_qec = test["y_qec"]

    all_y = all_y + list(y.flatten())              #all_y: Länge ist N*angles*noisepoints*bias=400*15*10*10 = 600k Elemente
    all_y_qec = all_y_qec + list(y_qec.flatten())

print("Dead files: ",len(faulty), ", ", faulty)
N = N - len(faulty)

data = np.full((noisepoints, 5, biaspoints), np.nan)      #Zahl zwischen noisepoints und biaspoints: bias+y+err + y_qec+err_qec = 3 + 2 = 5    FALLS mit QEC in npz file, sonst nur 3
for ö in range(noisepoints):
    data[ö, 0] = clean_file["bias"]
    err, err_qec = [], []
    y, y_qec = [], []
    for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
        hmm, hmm1 = [], []
        for i in range(N):
            for k in range(angles):
                hmm.append(all_y[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j + angles*ö])
                hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i + angles*noisepoints*j+angles*ö])
        err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
        y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
    data[ö, 1] = y
    data[ö, 2] = y_qec
    data[ö, 3] = err
    data[ö, 4] = err_qec

total = np.array(data, dtype=object)
print(np.shape(total))

Dead files:  0 ,  []
(6, 5, 7)


In [4]:
# name = "Repcode_d5"         #data = np.array((p, bias, y, y_qec))         code 1
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]
# noisepoints = len(p)

# b_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[1]               #alle nans rausfiltern
# b = b_all[~np.isnan(b_all)]
# biaspoints = len(b)

# faulty = []
# all_y, all_y_qec = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*noisepoints*bias=10*15*10*10 = 15000 Elemente
#     all_y_qec = all_y_qec + list(test[-1])

# print("Dead files: ",len(faulty), ", ", faulty)
# N = N - len(faulty)

# data = np.full((noisepoints, 5, biaspoints), np.nan)
# for ö in range(noisepoints):
#     data[ö, 0] = b
#     err, err_qec = [], []
#     y, y_qec = [], []
#     for j in range(biaspoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#         hmm, hmm1 = [], []
#         for i in range(N):
#             for k in range(angles):
#                 hmm.append(all_y[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#                 hmm1.append(all_y_qec[k+angles*noisepoints*biaspoints*i+angles*noisepoints*j+angles*ö])
#         err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#         y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))
#     data[ö, 1] = y
#     data[ö, 2] = y_qec
#     data[ö, 3] = err
#     data[ö, 4] = err_qec

# total = np.array(data, dtype=object)
# print(np.shape(total))

In [12]:
print(total)

np.save("text/{}.npy".format(name), data)

[[[-10000.0 -100.0 -10.0 0.0 10.0 100.0 10000.0]
  [0.069875 0.069875 0.07116666666666667 0.07270833333333333 0.06575
   0.07385416666666667 0.06877083333333334]
  [0.0665625 0.06860416666666666 0.06927083333333334 0.07102083333333334
   0.06979166666666667 0.07154166666666667 0.07183333333333333]
  [0.0019770947488254916 0.001962110055031459 0.002013965707347166
   0.0020387929747724466 0.0018564994688331528 0.002076498771943836
   0.001912234439775112]
  [0.001881892712747373 0.0019165185442462632 0.001923267148600074
   0.0019841078487420525 0.001976158166629644 0.002014660604056435
   0.0020113123364646317]]

 [[-10000.0 -100.0 -10.0 0.0 10.0 100.0 10000.0]
  [0.1733125 0.17202083333333335 0.18366666666666667 0.17495833333333333
   0.16560416666666666 0.16925 0.16572916666666668]
  [0.1588125 0.164625 0.1639375 0.1604375 0.17454166666666668
   0.16964583333333333 0.17854166666666665]
  [0.0029991105814080763 0.0030463001119565487 0.0031468236116110153
   0.0030567973644510383 0.002

In [ ]:
# name = "Repcode_d3_bias0_9"                       #alter Repcode, wo man für jede Simulation einen Plot hat   code 0
# N = 400
# angles = 15

# p_all = np.loadtxt('text/temp/{}0.txt'.format(name),delimiter=',')[0]               #alle nans rausfiltern
# p = p_all[~np.isnan(p_all)]

# datapoints = len(p)

# faulty = []
# all_y, all_y1 = [], []
# for i in range(N):
#     try:  
#         # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
#         test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
#     except FileNotFoundError:
#         faulty.append('{}'.format(i))
#         continue
#     all_y = all_y + list(test[-2])              #all_y: Länge ist N*angles*datapoints=10*15*10 = 1500 Elemente
#     all_y1 = all_y1 + list(test[-1])

# err, err_qec = [], []
# y, y_qec = [], []

# for j in range(datapoints):                 #std-err und mean ausrechnen aus allen messungen über alle winkel und jobs
#     hmm, hmm1 = [], []
#     for i in range(N):
#         for k in range(angles):
#             hmm.append(all_y[k+angles*datapoints*i+angles*j])
#             hmm1.append(all_y1[k+angles*datapoints*i+angles*j])
#     err.append(np.std(hmm)/np.sqrt(N*angles)), err_qec.append(np.std(hmm1)/np.sqrt(N*angles))
#     y.append(np.mean(hmm)), y_qec.append(np.mean(hmm1))

# print("Dead files: ",len(faulty), ", ", faulty)
# total = np.array((p,y,y_qec,err,err_qec))
# print(total)

In [2]:
N = 400                               #code OG
total = np.zeros((3,4))
faulty = []
name = "FTSteane_qec_4_7_neww"
for i in range(N):
    try:  
        # test=np.loadtxt('text/{}/{}{}.txt'.format(name,name,i),delimiter=',')                  #Mac
        test=np.loadtxt('text/temp/{}{}.txt'.format(name,i),delimiter=',')                        #Linux
    except FileNotFoundError:
        faulty.append('{}'.format(i))
        continue
    total=total+test
total = total/(N-len(faulty))
print("Dead files: ",len(faulty), ", ", faulty)
print(total)

Dead files:  0 ,  []
[[0.00044444 0.00055556 0.00066667 0.00077778]
 [0.16902083 0.18941667 0.19575    0.20435417]
 [0.05736907 0.06032394 0.0592164  0.06022282]]


In [3]:
#np.savetxt('text/FTSteane_3rd_q.txt', total, delimiter=",")
#np.savetxt('text/FTRotSurf_3rd_f+.txt', total, delimiter=",")
#np.savetxt('text/FTCarbon_e.txt', total, delimiter=",")

np.savetxt("text/{}.txt".format(name), total, delimiter=",")

#np.savetxt('text/FTCarbon_3rd_c+.txt', total, delimiter=",")

#np.savetxt('text/RotSurfFinal_d.txt', total, delimiter=",")
#np.savetxt('text/SteaneFinal_a+++.txt', total, delimiter=",")